### ISSUE TITLE
Unique ID's w/ eventer_autopost.R

### ISSUE THREAD

**Issue by ogsteele** [eventer-neuroscience/resources#2]
We discussed this this morning; and I'll do my best to describe what I'm experiencing here relatively succinctly. 

We would like to assign a unique ID (UID) to each submission in the repository. This would enable users to reference a model in the repository. Generating the sequence is easy ... 

```
# line 152
  # random string generator will be the UID for the file
  makeRandomString <- function(n=1, lenght=12)
  {
    randomString <- c(1:n) # initialize vector
    for (i in 1:n)
    {
      randomString[i] <- paste( c(sample(c(letters), 1),
                                  sample(c(0:9, letters),
                                         lenght - 1, replace=TRUE)),
                                collapse="", sep="")
    }
    return(randomString)
  }
```

... as is checking if the newly generated UID exists in the file path for the posts. ...

```
# line 188
# check if this random number exists and repeat if so
  rs <- "Example_Model"
  while (rs %in% list.files("content/post/") == TRUE) { rs <- makeRandomString() }
```

... however naming the folders the UIDs and generating the index.md's in those folders I couldn't seem to get to play nicely. This is important as we wanted the URL to match the UID for easy referencing etc. So currently I have it so that my version of autopost.R (eventer_autopost.R) creates the post the same way as your original script, then just renames them ... 

```
# line 242
# change folder name to UID (this will show up in the URL for the model now)
  system(paste('mv',
               # old foldername
               file.path(filePath, "content/post", filename),
               # new foldername
               file.path(filePath, "content/post", rs)
  ))


  # check whether the model is posted (created in the directory)

  post_df$UID <- rs # assign UID of the post
  target$UID[length(target$UID)] <- rs # change the last value to match the UID
  target$posted <- str_replace_all(string = target$UID,
                                   pattern = " ", replacement = "_") %in%
    list.files("content/post/")
```

There has to be a less clunky way of doing this. I'm also concerned about how it would work if I had multiple submissions. Currently `target$UID[length(target$UID)] <- rs # change the last value to match the UID` will find the last value in `target$UID` and change this to the UID. This is fine for when there's one post to be submitted, but when there's more than one this will skip the penultimate entry ... 

I suspect there are multiple other issues with my way of assigning UID's too that I'm missing, so point them out if you see them.

**Comment by amchagas** [comment]
@matiasandina if you have a  moment, we would really appreciate some input into this one! it is probably an easy fix, but since neither of us are R specialists, we are kind of stuck...

**Comment by matiasandina** [comment]
I would need to better understand the changes made to autopost.R. There is
a bit of code that can be simplified, such as the function to make IDs and
the system call yo move files (you can use file.rename in R). Still not
super sure about the file naming problem. It would be easier for me if you
can show the error you are getting.

**Comment by ogsteele** [comment]
Hi @matiasandina - thanks taking a look! 

I am almost certain that you're right (that my code should be better), that's just the best I could do to create a unique ID for each post. I was also not aware of file.rename in R, but can definitely integrate this instead of pasting to the shell like I did. 

I largely haven't changed the core structure of autopost.R much, simply adding in extra variables to some of the functions like makeBody to get it to post in the way we would need it for the website. 

What exactly do you mean by the 'file naming' problem? I know Andre and I had got a bit stuck on posted = TRUE in the google form not changing correctly as the file names weren't formatted correctly between what was on the google form and what is in the directory. I think I've gotten round this for the most part now. 

If however you're referring to where I said this:
`... however naming the folders the UIDs and generating the index.md's in those folders I couldn't seem to get to play nicely.`

That occurs when I tell Eventer autopost to create a folder name (to subsequently house index.md) that is equal to `rs` (the unique ID for the post) it will first create the foldername correctly, but then rename it to the post title. When creating the actual index.md file later however, it then tries to place the index.md folder in a file path with the UID altered folder which now doesn't exist ... ie ... 

- autopost creates a UID
- autopost creates a folder at `content/post/UID`
- autopost then renames this to `content/post/model_name`
- autopost then tries to write an index.md at `content/post/UID` which no longer exists. 

Sorry if I've totally missed either what you were saying, or an incredibly obvious fix in the code.

**Comment by matiasandina** [comment]
The issue you are seeing comes from who creates the folder and who writes the files (by design, two different unrelated functions).

You mess with the filenames and try to write here:
```
# actually write the md
lapply(1:nrow(post_df), function(x) write_md(post_df$filename[x], post_df$post[x]))
```
But previously you created a folder using the title inside `create_body()`.

```
root = "content/post"
if(title %in% list.files(root) == FALSE){
  # make dir
  dir.create(file.path(root, title))
}
```
It's difficult to create a solution without access to a reproducible environment.
A few recommendations.

1) Get rid of the function to generate strings. Use `stringi::stri_rand_strings(n=1, length=12, "[A-Z0-9]")` which is made for that.
2) Change the `system()` call to `file.rename(from, to)` You might need to use some handy base R functions like `basename()` and `dirname()`
3) Not sure why you are interactively setting the working directory. I'm almost 100% sure this is not what you want to be doing.

None of this solves your issue but cleans the code. Especially removing the `setwd()` call, which is a timebomb waiting to change your `list.files()` calls everywhere in unpredictable ways. For the rest, it's already a convoluted code (full of functions that would need to be split on different files instead of everything there, I am sorry about that, it is a pain to debug even for me and I wrote it!). Keeping lines shorter might help a bit with that.

4) I would check whether `list.files("content/post/")` gives you things that make sense. Because you are changing the working directory (see point 3), this is probably not working like I intended it. Check that the `str_replace_all(string = target$UID,                                   pattern = " ", replacement = "_")` command gives you something that makes sense and that the patterns are in the `list.files()` output. It's likely that this `%in%` hacky comparison will explode (they always do). If you show me the outputs for all this commands we can try to debug from there why posted is not turning to `TRUE` even though files are created.

**Comment by matiasandina** [comment]
Also, possibly not related with the issue but, because you are generating random strings to create IDs, if you don't have a correct functioning once, you are going to create many duplicates, which are going to be difficult to trace (all files are `index.md` inside random strings of alphanumerics). Keeping the strings in the google sheets `df` helps but that sheet also gets overwritten, so things might explode on that side (they have exploded for us when changing the title conventions for punctuation bugs).
So it might be advised to nuke the folder before trying any debugging when things go south.

**Comment by ogsteele** [comment]
Can't thank you enough for your advice here! I've gone through and implemented pretty much all of what you've suggested in 35545d2 the code now operates a little cleaner, so thanks.  Let me know if any of that looks horrendous! It seems to work on my end

In my defence the reason I had the interactive setwd() call was whilst were toying with creating separate "post" folders for different topics and wanted a user inout to select with "post" folder. We never ended up going that way, so it's fine to not have it. Just means the .Rproj has to be loaded for the script to work correctly with "content/post/" actually being in the right place. 

`list.files("content/post/")` correctly produces something that makes sense to me, so I'm not too concerned by this. 

The issue I suspect will be when post_df contains more than one post. Currently, the UID only generates a single UID 

```
rs <- "Example_Model"
  while (rs %in% list.files("content/post/") == TRUE) { rs <- stringi::stri_rand_strings(n=1, length=12, "[a-z0-9]") } 
```  
and then simply just assign this UID to the last value in post_df which is always empty  ...

```
post_df$UID <- rs # assign UID of the post
  target$UID[length(target$UID)] <- rs # change the last value to match the UID
  target$posted <- str_replace_all(string = target$UID,
                                   pattern = " ", replacement = "_") %in%
    list.files("content/post/")
```  

this is fine when post_df only has one post, but when it's got more than one, I'll have empty values here, no? Any thoughts on how to get round this?

**Comment by matiasandina** [comment]
This is something I didn't fully understand but I thought it was not part of the problem. Assigning at the end "because it's empty" it's fertile ground for explosions. R is made to use `data.frame`s (and lists, because `data.frame`s are lists).
I believe you should be generating your IDs like this
```
post_df %>%
  # if it is empty, give me a new id, else keep UID
  mutate(UID = ifelse(is.na(UID),
                                  stringi::stri_rand_strings(n=1, length=12, "[a-z0-9]"),
                                  UID))
```
And keeping the UID column on the spreadsheet that gets written to
So check for the place where we `select()` the original columns only. You want to add UID to those original columns so that UID is updated.
This will also help you keep a record of whether a post was processed (because it was given an ID) and prevent the same post having more than one ID because file paths suddenly didn't match.

My understanding is that posts will get generated *before* you run this code, so you will have data with info on other entries but with empty `UID` (hence we can use the `ifelse(...)`). Is this wrong?

**Comment by ogsteele** [comment]
Sorry for the delaying in getting back to you - I was trying to resolve the issues like you suggested but kept coming up against an issue where I'd created a UID earlier (checked against the existing list of file paths) and then created another UID later on. 

I think you're right, in that the post is generated first, and we assign UID's later. This seemed a little clunky, and my R is not as fluent as yours so I struggled to implement some of the `ifelse(...)` type stuff. Working with Andy we resolved it a slightly different way, albeit probably less classically R, but more like Python/MATLAB. I've put these changes in https://github.com/eventer-neuroscience/resources/commit/1a9c6589870f1fead20b4073af5ea4d4b8753dad 

Essentially we just run the loop checking existing UIDs and creating new UIDs and assign this to the `target` variable. 

```
  # check if this random number exists and repeat if so
  rs <- "Example_Model"
  n_NA <- sum(is.na(target$UID)) # number of NA values in target$UID (equivalent to unposted)
  i_NA <- which(is.na(target$UID)) # index of NA values (less explosive than "last two" etc)
  file_names <- list.files("content/post/")
  # create for loop adding checked UID's to the file_names variable we just assigned
  # as this isn't sorted, we can use tails later in "filename = file.path("content/post", tail(file_names,n_NA), "index.md"))"
  for (i in 1:n_NA) {
  while (rs %in% file_names == TRUE) { rs <- stringi::stri_rand_strings(n=1, length=12, "[a-z0-9]") }
    file_names <- c(file_names, rs)
    target$UID[i_NA[i]] <- rs
  }
```

This is then used to generate the `post_df` variable and later written to googlesheets. Getting the UID into `target`, (and importantly before the `createbody()` function is called), is necessary as we not only name the folder with the UID but also reference it in the post itself for others to be able to reference they're own post, so creating and assigning it later was problematic! 


I'm hoping this code is a little less explosive. We've tested it with multiple unposted entries too and it seems to be working fine now I think. Can't thank you enough for your help @matiasandina - definitely pushed us in a better direction!

**Comment by matiasandina** [comment]
Good to know you solved this! Yes the order of creation of things is key. A `while` loop inside a `for` loop looks a lot like python :sweat_smile:
